package org.firstinspires.ftc.teamcode.opmodes.auto.generated;

import com.pedropathing.api.Paths;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.ivy.Command;
import com.pedropathing.math.Pose;
import com.pedropathing.paths.Path;

import org.firstinspires.ftc.teamcode.autokit.AutoKit;

/**
 * Generated by the Auto Builder from red-garden-no-turret.pp. Do not edit: change the .pp and export again.
 */
public final class RedGardenNoTurretAuto {

    private RedGardenNoTurretAuto() {}

    /** The .pp file this was generated from. */
    public static final String SOURCE = "red-garden-no-turret.pp";

    /** Registered robot actions this Auto uses; checked when the OpMode initialises. */
    public static final String[] ACTIONS = {"IntakeOff", "IntakeOn", "ShootAll"};

    /** Registered robot conditions this Auto uses; checked when the OpMode initialises. */
    public static final String[] CONDITIONS = {"IntakeFull", "Tip1"};

    /** The alliance the Auto was drawn for ("RED" or "BLUE"); the other alliance runs it mirrored. */
    public static final String DRAWN_FOR = "RED";

    /** Where the robot starts, for the given alliance. */
    public static Pose startPose(boolean mirrored) {
        return poses(mirrored).of(60, 9, 90);
    }

    private static PoseFactory poses(boolean mirrored) {
        return mirrored ? PoseFactory.degrees().mirrorX(70.75) : PoseFactory.degrees();
    }

    /** Builds the whole Auto. Call once, at init; schedule the result at start. */
    public static Command build(AutoKit kit, boolean mirrored) {
        PoseFactory p = poses(mirrored);

        // Named points (x, y in inches, heading in degrees, Pedro field frame).
        Pose start = p.of(60, 9, 90);
        Pose collectAhead = p.of(60, 21, 90);
        Pose collectLeft = p.of(55.9, 20.3, 110);
        Pose hiveEntrance = p.of(60, 33, 90);
        Pose corridorExit = p.of(60, 104, 90);
        Pose clearToTurn = p.of(52, 112, 90);
        Pose rearShot = p.of(52, 110, 284.3);
        Pose loadingFlower = p.of(47, 124, 90);
        Pose flowerShot = p.of(47, 122, 287.3);
        Pose park = p.of(16, 106, 0);
        Pose gardenSide = p.of(40, 30, 0);
        Pose gardenFlower = p.of(18, 47.5, 180);
        Pose gardenShot = p.of(24, 47.5, 20.7);
        Pose collectHome = p.of(60, 10, 90);

        // Other poses the paths need (control points, unnamed endpoints).
        Pose toGardenSide = p.of(40, 30, 90);
        Pose gardenToPark = p.of(16, 106, 20.7);
        Pose toPark = p.of(16, 106, 287.3);

        // Keep-out zones (from the .pp `shapes`), corners in order.
        kit.keepOut(p.of(46.6, 51.2, 0), p.of(49.4, 51.2, 0), p.of(49.4, 90.3, 0), p.of(46.6, 90.3, 0)); // HIVE frame leg (red side)
        kit.keepOut(p.of(92.6, 51.2, 0), p.of(95, 51.2, 0), p.of(95, 90.3, 0), p.of(92.6, 90.3, 0)); // HIVE frame leg (blue side)
        kit.keepOut(p.of(70.8, 0, 0), p.of(141.5, 0, 0), p.of(141.5, 141.5, 0), p.of(70.8, 141.5, 0)); // Blue half: stay out

        // Paths, written as the stock Visualizer export writes them.
        Path pass1Ahead = Paths.line(start, collectAhead).constant(collectAhead);
        Path pass1Back = Paths.line(collectAhead, collectHome).constant(collectHome);
        Path pass2Left = Paths.line(collectHome, collectLeft).linear(collectHome, collectLeft);
        Path pass2Back = Paths.line(collectLeft, collectHome).linear(collectLeft, collectHome);
        Path toGardenSidePath = Paths.line(collectHome, toGardenSide).constant(toGardenSide);
        Path toGardenFlower = Paths.line(toGardenSide, gardenFlower).linear(toGardenSide, gardenFlower);
        Path turnToGardenCell = Paths.line(gardenFlower, gardenShot).linear(gardenFlower, gardenShot);
        Path gardenToParkPath = Paths.line(gardenShot, gardenToPark).constant(gardenToPark);
        Path toHiveEntrance = Paths.line(collectHome, hiveEntrance).constant(hiveEntrance);
        Path underHive = Paths.line(hiveEntrance, corridorExit).constant(corridorExit);
        Path clearToTurnPath = Paths.line(corridorExit, clearToTurn).constant(clearToTurn);
        Path turnToLoadingCell = Paths.line(clearToTurn, rearShot).linear(clearToTurn, rearShot);
        Path toLoadingFlower = Paths.line(rearShot, loadingFlower).linear(rearShot, loadingFlower);
        Path turnToLoadingCellAgain = Paths.line(loadingFlower, flowerShot).linear(loadingFlower, flowerShot);
        Path toParkPath = Paths.line(flowerShot, toPark).constant(toPark);

        return kit.sequence(
                kit.action("ShootAll"),
                kit.firstOf("Did our HIVE tip?",
                        kit.when("Tip1").then(
                                kit.guarded("If tipped", toParkPath, 1.6,
                                        kit.action("IntakeOn"),
                                        kit.path("Pass1Ahead", pass1Ahead),
                                        kit.path("Pass1Back", pass1Back),
                                        kit.path("Pass2Left", pass2Left),
                                        kit.path("Pass2Back", pass2Back),
                                        kit.action("IntakeOff"),
                                        kit.path("ToHiveEntrance", toHiveEntrance),
                                        kit.path("UnderHive", underHive),
                                        kit.path("ClearToTurn", clearToTurnPath),
                                        kit.path("TurnToLoadingCell", turnToLoadingCell),
                                        kit.action("ShootAll"),
                                        kit.path("ToLoadingFlower", toLoadingFlower, new String[] {}, AutoKit.at(0.7, "IntakeOn")),
                                        kit.firstOf("Take 4 POLLEN from the RED_LOADING FLOWER",
                                                kit.when("IntakeFull"),
                                                kit.afterMs(1500)),
                                        kit.action("IntakeOff"),
                                        kit.path("TurnToLoadingCellAgain", turnToLoadingCellAgain),
                                        kit.action("ShootAll"),
                                        kit.path("ToPark", toParkPath))),
                        kit.afterMs(5000).then(
                                kit.guarded("If not tipped", gardenToParkPath, 2.1,
                                        kit.path("ToGardenSide", toGardenSidePath),
                                        kit.path("ToGardenFlower", toGardenFlower, new String[] {}, AutoKit.at(0.7, "IntakeOn")),
                                        kit.firstOf("Take 4 POLLEN from the RED_GARDEN FLOWER",
                                                kit.when("IntakeFull"),
                                                kit.afterMs(1500)),
                                        kit.action("IntakeOff"),
                                        kit.path("TurnToGardenCell", turnToGardenCell),
                                        kit.action("ShootAll"),
                                        kit.path("GardenToPark", gardenToParkPath)))));
    }
}
