package org.firstinspires.ftc.teamcode.opmodes.auto.generated;

import com.pedropathing.api.Paths;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.ivy.Command;
import com.pedropathing.math.Pose;
import com.pedropathing.paths.Path;

import org.firstinspires.ftc.teamcode.autokit.AutoKit;

/**
 * Generated by the Auto Builder from red-garden-basic.pp. Do not edit: change the .pp and export again.
 */
public final class RedGardenBasicAuto {

    private RedGardenBasicAuto() {}

    /** The .pp file this was generated from. */
    public static final String SOURCE = "red-garden-basic.pp";

    /** Registered robot actions this Auto uses; checked when the OpMode initialises. */
    public static final String[] ACTIONS = {"IntakeOff", "IntakeOn", "ShootAll"};

    /** Registered robot conditions this Auto uses; checked when the OpMode initialises. */
    public static final String[] CONDITIONS = {"CameraBlind", "HiveTipped", "IntakeFull"};

    /** The alliance the Auto was drawn for ("RED" or "BLUE"); the other alliance runs it mirrored. */
    public static final String DRAWN_FOR = "RED";

    /** Where the robot starts, for the given alliance. */
    public static Pose startPose(boolean mirrored) {
        return poses(mirrored).of(60, 9, 90);
    }

    private static PoseFactory poses(boolean mirrored) {
        return mirrored ? PoseFactory.degrees().mirrorX(70.75) : PoseFactory.degrees();
    }

    /** Builds the whole Auto. Call once, at init; schedule the result at start. */
    public static Command build(AutoKit kit, boolean mirrored) {
        PoseFactory p = poses(mirrored);

        // Named points (x, y in inches, heading in degrees, Pedro field frame).
        Pose start = p.of(60, 9, 90);
        Pose collectAhead = p.of(60, 21, 90);
        Pose collectLeft = p.of(55.9, 20.3, 110);
        Pose hiveEntrance = p.of(60, 33, 90);
        Pose rearShot = p.of(60, 104, 90);
        Pose loadingFlower = p.of(47, 124, 90);
        Pose park = p.of(18, 106, 90);
        Pose collectHome = p.of(60, 10, 90);

        // Keep-out zones (from the .pp `shapes`), corners in order.
        kit.keepOut(p.of(46.6, 51.2, 0), p.of(49.4, 51.2, 0), p.of(49.4, 90.3, 0), p.of(46.6, 90.3, 0)); // HIVE frame leg (red side)
        kit.keepOut(p.of(92.6, 51.2, 0), p.of(95, 51.2, 0), p.of(95, 90.3, 0), p.of(92.6, 90.3, 0)); // HIVE frame leg (blue side)
        kit.keepOut(p.of(70.8, 0, 0), p.of(141.5, 0, 0), p.of(141.5, 141.5, 0), p.of(70.8, 141.5, 0)); // Blue half: stay out

        // Paths, written as the stock Visualizer export writes them.
        Path pass1Ahead = Paths.line(start, collectAhead).constant(collectAhead);
        Path pass1Back = Paths.line(collectAhead, collectHome).constant(collectHome);
        Path pass2Left = Paths.line(collectHome, collectLeft).linear(collectHome, collectLeft);
        Path pass2Back = Paths.line(collectLeft, collectHome).linear(collectLeft, collectHome);
        Path toHiveEntrance = Paths.line(collectHome, hiveEntrance).constant(hiveEntrance);
        Path underHive = Paths.line(hiveEntrance, rearShot).constant(rearShot);
        Path toLoadingFlower = Paths.line(rearShot, loadingFlower).constant(loadingFlower);
        Path toPark = Paths.line(loadingFlower, park).constant(park);

        return kit.sequence(
                kit.action("ShootAll"),
                kit.firstOf("Did our HIVE tip?",
                        kit.when("HiveTipped", "CameraBlind").then(
                                kit.guarded("If tipped", toPark, 1.6,
                                        kit.action("IntakeOn"),
                                        kit.path("Pass1Ahead", pass1Ahead),
                                        kit.path("Pass1Back", pass1Back),
                                        kit.path("Pass2Left", pass2Left),
                                        kit.path("Pass2Back", pass2Back),
                                        kit.action("IntakeOff"),
                                        kit.path("ToHiveEntrance", toHiveEntrance),
                                        kit.path("UnderHive", underHive),
                                        kit.action("ShootAll"),
                                        kit.path("ToLoadingFlower", toLoadingFlower, new String[] {}, AutoKit.at(0.7, "IntakeOn")),
                                        kit.firstOf("Take 4 POLLEN from the LOADING FLOWER",
                                                kit.when("IntakeFull"),
                                                kit.afterMs(1500)),
                                        kit.action("IntakeOff"),
                                        kit.action("ShootAll"),
                                        kit.path("ToPark", toPark))),
                        kit.afterMs(5000).then(
                                kit.guarded("If not tipped", toPark, 1.6,
                                        kit.path("ToHiveEntrance", toHiveEntrance),
                                        kit.path("UnderHive", underHive),
                                        kit.path("ToLoadingFlower", toLoadingFlower, new String[] {}, AutoKit.at(0.7, "IntakeOn")),
                                        kit.firstOf("Take 4 POLLEN from the LOADING FLOWER",
                                                kit.when("IntakeFull"),
                                                kit.afterMs(1500)),
                                        kit.action("IntakeOff"),
                                        kit.action("ShootAll"),
                                        kit.path("ToPark", toPark)))));
    }
}
