package org.firstinspires.ftc.teamcode.opmodes.auto.generated;

import com.pedropathing.api.Paths;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.ivy.Command;
import com.pedropathing.math.Pose;
import com.pedropathing.paths.Path;

import org.firstinspires.ftc.teamcode.autokit.AutoKit;

/**
 * Generated by the Auto Builder from red-simple.pp. Do not edit: change the .pp and export again.
 */
public final class RedSimpleAuto {

    private RedSimpleAuto() {}

    /** The .pp file this was generated from. */
    public static final String SOURCE = "red-simple.pp";

    /** Registered robot commands this Auto uses; checked when the OpMode initialises. */
    public static final String[] COMMANDS = {"LaunchAll"};

    /** Registered robot triggers this Auto uses; checked when the OpMode initialises. */
    public static final String[] TRIGGERS = {"RightCellDown"};

    /** The alliance the Auto was drawn for ("RED" or "BLUE"); the other alliance runs it mirrored. */
    public static final String DRAWN_FOR = "RED";

    /** Where the robot starts, for the given alliance. */
    public static Pose startPose(boolean mirrored) {
        return poses(mirrored).of(60, 9, 90);
    }

    private static PoseFactory poses(boolean mirrored) {
        return mirrored ? PoseFactory.degrees().mirrorX(70.75) : PoseFactory.degrees();
    }

    /** Builds the whole Auto. Call once, at init; schedule the result at start. */
    public static Command build(AutoKit kit, boolean mirrored) {
        PoseFactory p = poses(mirrored);

        // Named points (x, y in inches, heading in degrees, Pedro field frame).
        Pose start = p.of(60, 9, 90);
        Pose rearShot = p.of(60, 110, 90);
        Pose garden = p.of(24, 14, 180);

        // Other poses the paths need (control points, unnamed endpoints).
        Pose toGardenControl1 = p.of(40, 28, 0);

        // Keep-out zones (from the .pp `shapes`), corners in order.
        kit.keepOut(p.of(46.6, 51.2, 0), p.of(49.4, 51.2, 0), p.of(49.4, 90.3, 0), p.of(46.6, 90.3, 0)); // HIVE frame leg (red side)
        kit.keepOut(p.of(92.6, 51.2, 0), p.of(95, 51.2, 0), p.of(95, 90.3, 0), p.of(92.6, 90.3, 0)); // HIVE frame leg (blue side)
        kit.keepOut(p.of(70.8, 0, 0), p.of(141.5, 0, 0), p.of(141.5, 141.5, 0), p.of(70.8, 141.5, 0)); // Blue half: stay out

        // Paths, written as the stock Visualizer export writes them.
        Path underHive = Paths.line(start, rearShot).constant(rearShot);
        Path toGarden = Paths.curve(start, toGardenControl1, garden).linear(start, garden);

        return kit.sequence(
                kit.command("LaunchAll"),
                kit.firstOf("Did our HIVE tip?",
                        kit.when("RightCellDown").then(
                                kit.path("UnderHive", underHive),
                                kit.command("LaunchAll")),
                        kit.afterMs(3000).then(
                                kit.path("ToGarden", toGarden))));
    }
}
