package org.firstinspires.ftc.teamcode.opmodes.auto.generated;

import com.pedropathing.api.Paths;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.ivy.Command;
import com.pedropathing.math.Pose;
import com.pedropathing.paths.Path;

import org.firstinspires.ftc.teamcode.autokit.AutoKit;

/**
 * Generated by the Auto Builder from red-spot-map.pp. Do not edit: change the .pp and export again.
 */
public final class RedSpotMapAuto {

    private RedSpotMapAuto() {}

    /** The .pp file this was generated from. */
    public static final String SOURCE = "red-spot-map.pp";

    /** Registered robot commands this Auto uses; checked when the OpMode initialises. */
    public static final String[] COMMANDS = {};

    /** Registered robot triggers this Auto uses; checked when the OpMode initialises. */
    public static final String[] TRIGGERS = {};

    /** The alliance the Auto was drawn for ("RED" or "BLUE"); the other alliance runs it rotated half a turn about the field centre. */
    public static final String DRAWN_FOR = "RED";

    /** Where the robot starts, for the given alliance. */
    public static Pose startPose(boolean rotated) {
        return poses(rotated).of(59, 9.5, 90);
    }

    private static PoseFactory poses(boolean rotated) {
        return rotated ? PoseFactory.degrees().mirrorAroundPoint(70.75, 70.75) : PoseFactory.degrees();
    }

    /** Builds the whole Auto. Call once, at init; schedule the result at start. */
    public static Command build(AutoKit kit, boolean rotated) {
        PoseFactory p = poses(rotated);

        // Named points (x, y in inches, heading in degrees, Pedro field frame).
        Pose rIGHTSTART = p.of(59, 9.5, 90);
        Pose rIGHTHIVEENTRANCE = p.of(59, 47, 90);
        Pose lEFTHIVEENTRANCE = p.of(59, 94.7, 90);
        Pose lEFTDUMP = p.of(59, 117.8, 308);
        Pose lEFTFLOWER = p.of(47.5, 129, 90);
        Pose lEFTSTART = p.of(59, 132, 270);
        Pose lEFTLOADINGZONE = p.of(16, 115.7, 90);
        Pose rIGHTLOADINGZONE = p.of(16, 96.6, 90);
        Pose yOURWALLFLOWER = p.of(15.2, 47.8, 180);
        Pose rIGHTDUMP = p.of(59, 23.7, 52);
        Pose gARDEN = p.of(10.5, 11.8, 180);

        // Paths, written as the stock Visualizer export writes them.
        Path toRIGHTHIVEENTRANCE = Paths.line(rIGHTSTART, rIGHTHIVEENTRANCE).linear(rIGHTSTART, rIGHTHIVEENTRANCE);
        Path toLEFTHIVEENTRANCE = Paths.line(rIGHTHIVEENTRANCE, lEFTHIVEENTRANCE).linear(rIGHTHIVEENTRANCE, lEFTHIVEENTRANCE);
        Path toLEFTDUMP = Paths.line(lEFTHIVEENTRANCE, lEFTDUMP).linear(lEFTHIVEENTRANCE, lEFTDUMP);
        Path toLEFTFLOWER = Paths.line(lEFTDUMP, lEFTFLOWER).linear(lEFTDUMP, lEFTFLOWER);
        Path toLEFTSTART = Paths.line(lEFTFLOWER, lEFTSTART).linear(lEFTFLOWER, lEFTSTART);
        Path toLEFTLOADINGZONE = Paths.line(lEFTSTART, lEFTLOADINGZONE).linear(lEFTSTART, lEFTLOADINGZONE);
        Path toRIGHTLOADINGZONE = Paths.line(lEFTLOADINGZONE, rIGHTLOADINGZONE).linear(lEFTLOADINGZONE, rIGHTLOADINGZONE);
        Path toYOURWALLFLOWER = Paths.line(rIGHTLOADINGZONE, yOURWALLFLOWER).linear(rIGHTLOADINGZONE, yOURWALLFLOWER);
        Path toRIGHTDUMP = Paths.line(yOURWALLFLOWER, rIGHTDUMP).linear(yOURWALLFLOWER, rIGHTDUMP);
        Path toGARDEN = Paths.line(rIGHTDUMP, gARDEN).linear(rIGHTDUMP, gARDEN);

        return kit.sequence(
                kit.path("to RIGHT_HIVE_ENTRANCE", toRIGHTHIVEENTRANCE),
                kit.path("to LEFT_HIVE_ENTRANCE", toLEFTHIVEENTRANCE),
                kit.path("to LEFT_DUMP", toLEFTDUMP),
                kit.path("to LEFT_FLOWER", toLEFTFLOWER),
                kit.path("to LEFT_START", toLEFTSTART),
                kit.path("to LEFT_LOADING_ZONE", toLEFTLOADINGZONE),
                kit.path("to RIGHT_LOADING_ZONE", toRIGHTLOADINGZONE),
                kit.path("to YOUR_WALL_FLOWER", toYOURWALLFLOWER),
                kit.path("to RIGHT_DUMP", toRIGHTDUMP),
                kit.path("to GARDEN", toGARDEN));
    }
}
