// Draws public/robot.svg and public/robot.png, the robot the field shows, from a few measurements.
//
//   node scripts/robot-image.mjs
//
// How the Visualizer uses the image (src/lib/components/RobotSprite.svelte): it stretches it to the
// Robot Width x Robot Height settings (inches; our Autos save 18 x 18) and rotates it by the robot's
// heading about its centre. At heading 0 the robot faces +x, which is right on the field. So:
//
//   - the image's RIGHT edge is the robot's front, its top edge the robot's left side;
//   - the image's centre is the point the path follows (Pedro's robot pose);
//   - the whole image is the footprint the paths are planned with (ENVELOPE below), so draw it edge
//     to edge. The real chassis is drawn inside it, to scale, at its measured size.
//
// Change a number below, run this again, and commit both files. The PNG is what saved Autos load
// ("robotImage": "/robot.png"); the SVG is the same drawing, kept for editing and for crisp zoom.
// Rendering the PNG needs a Chromium: Playwright's, or set CHROME to one.

import { writeFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

// ---- Measurements, inches. Front is +x, left is +y, origin at the chassis centre. ----------------
// The footprint the Autos plan with: the 18 in start-size limit, which the robot grows toward.
const ENVELOPE = 18;
// The chassis today (5 Oct 2026, from the top-down photo of 19429's drive base): about 11 x 11 in.
const CHASSIS_LENGTH = 11; // front to back
const CHASSIS_WIDTH = 11; // side to side
// goBILDA 104 mm mecanum wheels: 4.1 in across. Width and placement are nominal; measure to refine.
const WHEEL_DIA = 4.1;
const WHEEL_WIDTH = 1.5;
const WHEEL_INSET = 0.5; // wheel edge to the chassis' front or back edge
// The intake: a roller across the front edge, between the front wheels.
const ROLLER_DIA = 1.0;
const ROLLER_GAP = 0.3; // roller end to the wheel beside it

// ---- Drawing -----------------------------------------------------------------------------------
const PX = 1000 / ENVELOPE; // pixels per inch in the PNG
const S = ENVELOPE * PX;
const sx = (x) => (x + ENVELOPE / 2) * PX; // robot x (front) -> image x (right)
const sy = (y) => (ENVELOPE / 2 - y) * PX; // robot y (left) -> image y (down)
const f = (v) => +v.toFixed(1);

function rect(cx, cy, length, width, attrs) {
  return `<rect x="${f(sx(cx - length / 2))}" y="${f(sy(cy + width / 2))}" width="${f(length * PX)}" height="${f(width * PX)}" ${attrs}/>`;
}

const L2 = CHASSIS_LENGTH / 2;
const W2 = CHASSIS_WIDTH / 2;
const wheelX = L2 - WHEEL_INSET - WHEEL_DIA / 2;
const wheelY = W2 - WHEEL_WIDTH / 2;

// A mecanum wheel seen from above, its rollers at 45 deg in the usual "X" (the rollers' axes point
// toward the robot's centre): front-left and back-right lean one way, front-right and back-left the other.
function wheel(fx, fy) {
  const cx = fx * wheelX;
  const cy = fy * wheelY;
  const id = `wheel-${fx > 0 ? "f" : "b"}${fy > 0 ? "l" : "r"}`;
  const outline = (attrs) =>
    rect(cx, cy, WHEEL_DIA, WHEEL_WIDTH, `rx="${f(0.35 * PX)}" ${attrs}`);
  const parts = [
    `<clipPath id="${id}">${outline("")}</clipPath>`,
    outline(`fill="#1f2328"`),
    `<g clip-path="url(#${id})">`,
  ];
  const lean = fx * fy; // +1: front-left / back-right
  const n = 5;
  for (let i = 0; i < n; i++) {
    const along = (i - (n - 1) / 2) * (WHEEL_DIA / n);
    const h = WHEEL_WIDTH / 2 - 0.15;
    // A roller's axis at 45 deg: from (along - h*lean, -h) to (along + h*lean, +h) in (x, y) about the wheel centre.
    const x1 = cx + along - h * lean;
    const y1 = cy - h;
    const x2 = cx + along + h * lean;
    const y2 = cy + h;
    parts.push(
      `<line x1="${f(sx(x1))}" y1="${f(sy(y1))}" x2="${f(sx(x2))}" y2="${f(sy(y2))}" stroke="#f2c200" stroke-width="${f(0.22 * PX)}" stroke-linecap="round"/>`,
    );
  }
  parts.push(
    "</g>",
    outline(`fill="none" stroke="#f2c200" stroke-width="${f(0.12 * PX)}"`),
  );
  return parts.join("\n  ");
}

const rollerHalf = W2 - WHEEL_WIDTH - ROLLER_GAP;
const rollerX = L2 - ROLLER_DIA / 2;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${S}" height="${S}" viewBox="0 0 ${S} ${S}">
  <!-- Generated by scripts/robot-image.mjs: change the measurements there, not here. Right = front. -->
  <!-- The planning footprint (${ENVELOPE} x ${ENVELOPE} in): what the paths are checked against. -->
  <rect x="${f(0.15 * PX)}" y="${f(0.15 * PX)}" width="${f(S - 0.3 * PX)}" height="${f(S - 0.3 * PX)}" fill="none" stroke="#e8e8e8" stroke-opacity="0.85" stroke-width="${f(0.2 * PX)}" stroke-dasharray="${f(0.9 * PX)} ${f(0.6 * PX)}"/>
  <!-- The chassis (${CHASSIS_LENGTH} x ${CHASSIS_WIDTH} in). -->
  ${rect(0, 0, CHASSIS_LENGTH, CHASSIS_WIDTH, `fill="#c9ced4" fill-opacity="0.9" stroke="#5b636b" stroke-width="${f(0.25 * PX)}"`)}
  <!-- Mecanum wheels. -->
  ${wheel(1, 1)}
  ${wheel(1, -1)}
  ${wheel(-1, 1)}
  ${wheel(-1, -1)}
  <!-- The intake roller, on the front edge between the front wheels. -->
  ${rect(rollerX, 0, ROLLER_DIA, 2 * rollerHalf, `rx="${f((ROLLER_DIA / 2) * PX)}" fill="#ff7a00" stroke="#7a3a00" stroke-width="${f(0.1 * PX)}"`)}
  <!-- Front marker: an arrow from the centre toward the front. -->
  <path d="M ${f(sx(-1.6))} ${f(sy(0))} L ${f(sx(1.2))} ${f(sy(0))} M ${f(sx(0.2))} ${f(sy(1.1))} L ${f(sx(1.4))} ${f(sy(0))} L ${f(sx(0.2))} ${f(sy(-1.1))}" fill="none" stroke="#d1242f" stroke-width="${f(0.45 * PX)}" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="${f(sx(0))}" cy="${f(sy(0))}" r="${f(0.3 * PX)}" fill="#1f2328"/>
</svg>
`;

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const svgPath = path.join(root, "public", "robot.svg");
writeFileSync(svgPath, svg);
console.log(`wrote ${svgPath}`);

const chrome = [
  process.env.CHROME,
  "/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell",
].find((c) => c && existsSync(c));
if (!chrome) {
  console.log("No Chromium found (set CHROME): public/robot.png not updated.");
} else {
  const pngPath = path.join(root, "public", "robot.png");
  execFileSync(
    chrome,
    [
      "--headless",
      "--no-sandbox",
      "--disable-gpu",
      "--hide-scrollbars",
      `--window-size=${S},${S}`,
      "--default-background-color=00000000",
      `--screenshot=${pngPath}`,
      `file://${svgPath}`,
    ],
    { stdio: "ignore" },
  );
  console.log(`wrote ${pngPath}`);
}
